//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub plugin_function_id: String,
    pub display_name: Option<String>,
    pub description: Option<String>,
    pub r#type: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub resource_json: Option<String>,
    pub level: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plugin_function::Entity",
        from = "Column::PluginFunctionId",
        to = "super::plugin_function::Column::FunctionId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PluginFunction,
    #[sea_orm(has_many = "super::plugin_function_permission::Entity")]
    PluginFunctionPermission,
    #[sea_orm(has_many = "super::workflow_code_allowed_permission::Entity")]
    WorkflowCodeAllowedPermission,
}

impl Related<super::plugin_function::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginFunction.def()
    }
}

impl Related<super::plugin_function_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginFunctionPermission.def()
    }
}

impl Related<super::workflow_code_allowed_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCodeAllowedPermission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
