//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plugin_function_permission")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub plugin_function_id: String,
    pub permission_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::permission::Entity",
        from = "Column::PermissionId",
        to = "super::permission::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Permission,
    #[sea_orm(
        belongs_to = "super::plugin_function::Entity",
        from = "Column::PluginFunctionId",
        to = "super::plugin_function::Column::FunctionId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PluginFunction,
}

impl Related<super::permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permission.def()
    }
}

impl Related<super::plugin_function::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginFunction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
