//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plugin_function")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub function_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub package_id: String,
    pub function_name: String,
    pub description: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub arguments: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub returns: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::permission::Entity")]
    Permission,
    #[sea_orm(has_many = "super::plugin_function_permission::Entity")]
    PluginFunctionPermission,
    #[sea_orm(
        belongs_to = "super::plugin_package::Entity",
        from = "Column::PackageId",
        to = "super::plugin_package::Column::PackageId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PluginPackage,
    #[sea_orm(has_many = "super::workflow_code_plugin_function::Entity")]
    WorkflowCodePluginFunction,
}

impl Related<super::permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Permission.def()
    }
}

impl Related<super::plugin_function_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginFunctionPermission.def()
    }
}

impl Related<super::plugin_package::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginPackage.def()
    }
}

impl Related<super::workflow_code_plugin_function::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCodePluginFunction.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
