//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "plugin_package")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub package_id: String,
    pub package_name: String,
    pub package_version: String,
    pub description: Option<String>,
    pub plugin_store_url: Option<String>,
    pub internal_plugin: bool,
    pub verified: bool,
    pub deprecated: bool,
    pub installed_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::plugin_function::Entity")]
    PluginFunction,
    #[sea_orm(has_many = "super::workflow_code_plugin_package::Entity")]
    WorkflowCodePluginPackage,
}

impl Related<super::plugin_function::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginFunction.def()
    }
}

impl Related<super::workflow_code_plugin_package::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCodePluginPackage.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
