//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::model::Entity as Model;
pub use super::plugin_function::Entity as PluginFunction;
pub use super::plugin_function_permission::Entity as PluginFunctionPermission;
pub use super::plugin_package::Entity as PluginPackage;
pub use super::provider::Entity as Provider;
