//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::model::Entity as Model;
pub use super::permission::Entity as Permission;
pub use super::plugin_function::Entity as PluginFunction;
pub use super::plugin_function_permission::Entity as PluginFunctionPermission;
pub use super::plugin_package::Entity as PluginPackage;
pub use super::provider::Entity as Provider;
pub use super::workflow::Entity as Workflow;
pub use super::workflow_code::Entity as WorkflowCode;
pub use super::workflow_code_allowed_permission::Entity as WorkflowCodeAllowedPermission;
pub use super::workflow_code_plugin_function::Entity as WorkflowCodePluginFunction;
pub use super::workflow_code_plugin_package::Entity as WorkflowCodePluginPackage;
pub use super::workflow_result::Entity as WorkflowResult;
