//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "workflow_code_plugin_function")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub workflow_code_id: String,
    pub plugin_function_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::plugin_function::Entity",
        from = "Column::PluginFunctionId",
        to = "super::plugin_function::Column::FunctionId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    PluginFunction,
    #[sea_orm(
        belongs_to = "super::workflow_code::Entity",
        from = "Column::WorkflowCodeId",
        to = "super::workflow_code::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    WorkflowCode,
}

impl Related<super::plugin_function::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PluginFunction.def()
    }
}

impl Related<super::workflow_code::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCode.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
