//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "workflow")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub display_name: String,
    pub description: Option<String>,
    pub workflow_language: i32,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::workflow_code::Entity")]
    WorkflowCode,
    #[sea_orm(has_many = "super::workflow_result::Entity")]
    WorkflowResult,
}

impl Related<super::workflow_code::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCode.def()
    }
}

impl Related<super::workflow_result::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowResult.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
