//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "workflow_code")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub workflow_id: String,
    pub code_revision: i32,
    #[sea_orm(column_type = "Text")]
    pub code: String,
    pub language: i32,
    pub created_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::workflow::Entity",
        from = "Column::WorkflowId",
        to = "super::workflow::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Workflow,
    #[sea_orm(has_many = "super::workflow_code_allowed_permission::Entity")]
    WorkflowCodeAllowedPermission,
    #[sea_orm(has_many = "super::workflow_code_plugin_function::Entity")]
    WorkflowCodePluginFunction,
    #[sea_orm(has_many = "super::workflow_code_plugin_package::Entity")]
    WorkflowCodePluginPackage,
    #[sea_orm(has_many = "super::workflow_result::Entity")]
    WorkflowResult,
}

impl Related<super::workflow::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workflow.def()
    }
}

impl Related<super::workflow_code_allowed_permission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCodeAllowedPermission.def()
    }
}

impl Related<super::workflow_code_plugin_function::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCodePluginFunction.def()
    }
}

impl Related<super::workflow_code_plugin_package::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowCodePluginPackage.def()
    }
}

impl Related<super::workflow_result::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkflowResult.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
