// Sapphillon
// SPDX-FileCopyrightText: 2025 Yuta Takahashi
// SPDX-License-Identifier: MPL-2.0 OR GPL-3.0-or-later
//
// This file is automatically generated by build.rs
// DO NOT EDIT THIS FILE MANUALLY
//
// This file contains information about internal plugins discovered
// from the js_plugins directory during build time.

use entity::entity::plugin_package::Model as PluginPackage;

/// Returns a list of internal plugins discovered at build time.
///
/// This function returns plugin information for all internal plugins
/// found in the js_plugins directory. The plugins are returned in
/// alphabetical order by package_id for stable ordering.
pub fn internal_plugins() -> Vec<PluginPackage> {
    let mut plugins = Vec::new();

    plugins.push(PluginPackage {
        package_id: "app.sapphillon/example/1.0.0".to_string(),
        package_name: "example".to_string(),
        package_version: "1.0.0".to_string(),
        description: None,
        plugin_store_url: None,
        internal_plugin: true,
        verified: true,
        deprecated: false,
        installed_at: None,
        updated_at: None,
    });

    plugins.push(PluginPackage {
        package_id: "app.sapphillon/plugin-a/1.0.0".to_string(),
        package_name: "plugin-a".to_string(),
        package_version: "1.0.0".to_string(),
        description: None,
        plugin_store_url: None,
        internal_plugin: true,
        verified: true,
        deprecated: false,
        installed_at: None,
        updated_at: None,
    });

    plugins.push(PluginPackage {
        package_id: "app.sapphillon/plugin-b/1.0.0".to_string(),
        package_name: "plugin-b".to_string(),
        package_version: "1.0.0".to_string(),
        description: None,
        plugin_store_url: None,
        internal_plugin: true,
        verified: true,
        deprecated: false,
        installed_at: None,
        updated_at: None,
    });

    plugins.push(PluginPackage {
        package_id: "other.author/plugin-c/1.0.0".to_string(),
        package_name: "plugin-c".to_string(),
        package_version: "1.0.0".to_string(),
        description: None,
        plugin_store_url: None,
        internal_plugin: true,
        verified: true,
        deprecated: false,
        installed_at: None,
        updated_at: None,
    });

    plugins
}
